### ISSUE TITLE
Promises resolving more than once.

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo2#12]
It appears that https://github.com/dojo/dojo2/blob/master/tests/unit/Promise.ts#L59 is legitimately failing and that the Promise is resolving twice.

```
>> FAIL: main - Promise - #then - resolve once (2ms)
AssertionError: expected 2 to equal 1
  at Function.assert.strictEqual  <node_modules/intern/node_modules/chai/chai.js:2487:32>
  at <Promise.ts:59:11>
  at <node_modules/intern/lib/Test.js:116:16>
  at <Promise.ts:362:15>
  at run  <Promise.ts:237:7>
  at run  <Promise.ts:244:7>
  at <nextTick.ts:37:3>
  at process._tickCallback  <node.js:355:11>
FATAL ERROR
TypeError: Cannot read property '0' of null
  at runCallbacks  <Promise.ts:10:58>
  at <Promise.ts:303:4>
  at run  <Promise.ts:237:7>
  at <nextTick.ts:37:3>
  at process._tickCallback  <node.js:355:11>
```

**Comment by csnover** [comment]
Fixed by 78d9b19232231fe7b0f9d0af9e599491bb089fc2
